name: Prepare SD card images

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        description: 'The tag/ref to use (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v4
      - name: Prepare SD Card for MqGateway
        run:  |
          chmod +x installation-scripts/sdcard-image.sh
          sudo installation-scripts/sdcard-image.sh --system mqgateway -w /tmp/mqgateway
        shell: bash
      - name: Prepare SD Card for Raspberry Pi
        if: false # disabled because of the issue #81
        run:  |
          chmod +x installation-scripts/sdcard-image.sh
          sudo installation-scripts/sdcard-image.sh --system raspberrypi -w /tmp/raspberrypi
        shell: bash
      - name: Upload MqGateway SD card to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/mqgateway/armbian.img.xz
          asset_name: UniGateway_SDCardImage_MqGateway.img.xz
          tag: ${{ github.event.inputs.ref || github.ref }}
          overwrite: true
      - name: Upload Raspberry Pi SD card to release
        if: false # disabled because of the issue #81
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/raspberrypi/armbian.img.xz
          asset_name: UniGateway_SDCardImage_RaspberryPi.img.xz
          tag: ${{ github.event.inputs.ref || github.ref }}
          overwrite: true

