name: Prepare SD card images

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v2
      - name: Prepare SD Card for MqGateway
        run:  |
          chmod +x installation-scripts/sdcard-image.sh
          sudo installation-scripts/sdcard-image.sh --system mqgateway -w /tmp/mqgateway
        shell: bash
      - name: Prepare SD Card for Raspberry Pi
        run:  |
          chmod +x installation-scripts/sdcard-image.sh
          sudo installation-scripts/sdcard-image.sh --system raspberrypi -w /tmp/raspberrypi
        shell: bash
      - name: Upload MqGateway SD card to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/mqgateway/armbian.img.xz
          asset_name: UniGateway_SDCardImage_RaspberryPi.img.xz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Raspberry Pi SD card to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/raspberrypi/armbian.img.xz
          asset_name: UniGateway_SDCardImage_MqGateway.img.xz
          tag: ${{ github.ref }}
          overwrite: true

