name: Validate Pull Request

on:
  pull_request:
    branches: [ main ]
    paths-ignore: ["docs/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica
    - name: Run tests
      run: ./gradlew check shadowJar
    - name: Store tests results as artifact
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: tests-results
        path: build/reports/tests/
